# Verificar se o ponto de montagem /var tem pelo menos 40GB e 85% livre

# - name: Check /var freespace
#   command: df /var -m --output\=avail | tail -1
#   register: var_freespace

# - fail: 
#     msg: /var nao tem espaco suficiente para realizar a atualizacao do SO (40GB requerido)
#   when: var_freespace.stdout <= 40000

- name: Set a constant defining number of Bytes in 1 GB
  set_fact:
    const_bytes_in_gb: 1073741824

- name: Verify disk space in /var (if it exists)
  fail: msg="The available space on the /var partition is {{ (item.size_available|int / const_bytes_in_gb|int)|round(1) }} GB, but it should be at least {{ min_undercloud_disk_gb }} GB."
  with_items: "{{ ansible_mounts }}"
  when: "'/var' == '{{ item.mount }}'"
  failed_when: "{{ min_undercloud_disk_gb|int * const_bytes_in_gb|int }} >= {{ item.size_available|int }}"
  # Notify the next task that we've checked /var (and that it exists)
  changed_when: True
  register: previous
